apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-demowebsite
  labels:
    app: capstone-project-demowebsite
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project-demowebsite
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project-demowebsite
    spec:
      containers:
        - image: shikhas/capstone-project-demowebsite
          imagePullPolicy: Always
          name: capstone-project-demowebsite
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-demowebsite
  labels:
    app: capstone-project-demowebsite
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-demowebsite
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP