apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-devops
  labels:
    app: capstone-project-devops
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project-devops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project-devops
    spec:
      containers:
        - image: shikhas/capstone-project-devops
          imagePullPolicy: Always
          name: capstone-project-devops
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-devops
  labels:
    app: capstone-project-devops
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-devops
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP